#!/usr/bin/env php
<?php declare(strict_types=1);

define('CLI_MOD', true);

require_once 'bootstrap.php';

switch ($argv[1]) {
    case 'db':
        switch($argv[2]) {
            case 'migrate':
                \Lowel\Workproject\DB\Migrations\UserMigrations::migrateFromConfig();
                break;
            case 'reset':
                \Lowel\Workproject\DB\Migrations\UserMigrations::dropTablesFromConfig();
                break;
            case 'seed':
                \Lowel\Workproject\DB\Seed\Seeder::run();
        }
        break;

}